# fly.toml app configuration file generated for axum-solid-playground on 2024-02-07T15:57:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "axum-solid-playground"
primary_region = "ams"

[build]

# port: litefs proxy (see litefs.yml)
# min_machines_running = 1 for litefs to work properly
# https://github.com/superfly/litefs/issues/347
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "playground_litefs"
  destination = "/var/lib/litefs"

